#!/usr/bin/env php
<?php

if (PHP_VERSION_ID < 50400) {
    file_put_contents('php://stderr', sprintf(
        "Spaceport requires PHP 5.4 version or higher and your system has PHP %s version installed.\n\n",
        PHP_VERSION
    ));
    exit(1);
}

require __DIR__.'/vendor/autoload.php';

$appVersion = '@app_version@';

const BASE_DIR = __DIR__;

// Windows uses Path instead of PATH
if (!isset($_SERVER['PATH']) && isset($_SERVER['Path'])) {
    $_SERVER['PATH'] = $_SERVER['Path'];
}

$app = new Spaceport\Application('Spaceport', $appVersion);
if ('phar://' === substr(__DIR__, 0, 7)){
    $app->add(new Spaceport\Commands\SelfUpdateCommand());
}
$app->add(new Spaceport\Commands\InitCommand());
$app->add(new Spaceport\Commands\StartCommand());
$app->add(new Spaceport\Commands\StopCommand());
$app->add(new Spaceport\Commands\StatusCommand());
$app->add(new Spaceport\Commands\DatabaseCommand());
$app->add(new Spaceport\Commands\DestroyCommand());
$app->add(new Spaceport\Commands\NpmCommand());
$app->add(new Spaceport\Commands\GulpCommand());
$app->add(new Spaceport\Commands\GruntCommand());
$app->add(new Spaceport\Commands\BowerCommand());
$app->add(new Spaceport\Commands\CleanCommand());
$app->add(new Spaceport\Commands\PhpCommand());
$app->add(new Spaceport\Commands\RefreshVendorCommand());
$app->add(new Spaceport\Commands\SelfUpdateCommand());
$app->add(new Spaceport\Commands\SetupNfsCommand());

$app->run();
