#!/usr/bin/env php
<?php

if (PHP_VERSION_ID < 50600) {
    file_put_contents('php://stderr', sprintf(
        "Spaceport requires PHP 5.6 version or higher and your system has PHP %s version installed.\n\n",
        PHP_VERSION
    ));
    exit(1);
}

require __DIR__.'/vendor/autoload.php';

$appVersion = '@app_version@';

const BASE_DIR = __DIR__;

// Windows uses Path instead of PATH
if (!isset($_SERVER['PATH']) && isset($_SERVER['Path'])) {
    $_SERVER['PATH'] = $_SERVER['Path'];
}

$app = new Spaceport\Application('Spaceport', $appVersion);
$app->add(new Spaceport\Commands\InitCommand());
$app->add(new Spaceport\Commands\StartCommand());
$app->add(new Spaceport\Commands\CopyCommand());
$app->add(new Spaceport\Commands\StopCommand());
$app->add(new Spaceport\Commands\SslCommand());
$app->add(new Spaceport\Commands\CleanCommand());

$app->run();
